// LICENSE: GNU GPL v3 You should have received a copy of the GNU General
// Public License along with this program. If not, see
// https://www.gnu.org/licenses/.

/////////////////////// hightlight.mjs /////////////////////////////////
// Defines the highlight colors/styles for the open guide editor      //
// with its extensions, keymaps, settings, etc.                       //
////////////////////////////////////////////////////////////////////////

export default function getOgeStyle(HighlightStyle, tags) {
    return HighlightStyle.define([
       {tag: tags.lineComment, color: 'var(--gray5)' },
       {tag: tags.blockComment, color: 'var(--gray5)' },
       {tag: tags.docComment, color: 'var(--gray5)' },
       //{tag: tags.name, },
       //{tag: tags.variableName, },
       //{tag: tags.typeName, },
       //{tag: tags.tagName, },
       //{tag: tags.propertyName, },
       //{tag: tags.attributeName, },
       //{tag: tags.className, },
       //{tag: tags.labelName, },
       //{tag: tags.namespace, },
       //{tag: tags.macroName, },
       //{tag: tags.literal, },
       //{tag: tags.string, },
       //{tag: tags.docString, },
       //{tag: tags.character, },
       //{tag: tags.attributeValue, },
       //{tag: tags.number, },
       //{tag: tags.integer, },
       //{tag: tags.float, },
       //{tag: tags.bool, },
       //{tag: tags.regexp, },
       //{tag: tags.escape, },
       //{tag: tags.color, },
       {tag: tags.url, color: 'var(--blue)' },
       {tag: tags.keyword, color: 'var(--purple)' },
       //{tag: tags.self, },
       //{tag: tags.null, },
       //{tag: tags.atom, },
       //{tag: tags.unit, },
       //{tag: tags.modifier, },
       //{tag: tags.operatorKeyword, },
       //{tag: tags.controlKeyword, },
       //{tag: tags.definitionKeyword, },
       //{tag: tags.moduleKeyword, },
       //{tag: tags.operator, },
       //{tag: tags.derefOperator, },
       //{tag: tags.arithmeticOperator, },
       //{tag: tags.logicOperator, },
       //{tag: tags.bitwiseOperator, },
       //{tag: tags.compareOperator, },
       //{tag: tags.updateOperator, },
       //{tag: tags.definitionOperator, },
       //{tag: tags.typeOperator, },
       //{tag: tags.controlOperator, },
       //{tag: tags.punctuation, },
       //{tag: tags.separator, },
       //{tag: tags.bracket, },
       //{tag: tags.angleBracket, },
       {tag: tags.squareBracket, color: 'var(--green)' },
       //{tag: tags.paren, },
       //{tag: tags.brace, },
       //{tag: tags.content, },
       {tag: tags.heading, color: 'var(--purple)', fontWeight: 'bold', textDecoration: 'underline'},
       //{tag: tags.heading1, },
       //{tag: tags.heading2, },
       //{tag: tags.heading3, },
       //{tag: tags.heading4, },
       //{tag: tags.heading5, },
       //{tag: tags.heading6, },
       //{tag: tags.contentSeparator, },
       //{tag: tags.list, },
       {tag: tags.quote, color: 'var(--purple)'},
       {tag: tags.emphasis, color: 'var(--red)', fontStyle: 'italic' },
       {tag: tags.strong, color:'var(--purple)', fontWeight: 'bold' },
       {tag: tags.link, color: 'var(--blue)', textDecoration: 'underline'},
       {tag: tags.monospace, color: 'var(--gray3)' },
       {tag: tags.strikethrough, color: 'var(--lightred)', textDecoration: 'line-through'},
       //{tag: tags.inserted, },
       //{tag: tags.deleted, },
       //{tag: tags.changed, },
       {tag: tags.invalid, backgroundColor: 'var(--lightred)'},
       {tag: tags.meta, color: 'var(--green)'},
       {tag: tags.documentMeta, color: 'var(--green)'},
       {tag: tags.annotation, color: 'var(--purple)' }
    ]);
}
